package logic

const VA_SHAPE_SIZE = 4
const VA_PLAT_HEIGHT = 20
const VA_PLAT_WIDTH = 10
const VA_WALL_DEPTH = 2

const VA_WORLD_WIDTH = VA_PLAT_WIDTH + VA_WALL_DEPTH*2
const VA_WORLD_HEIGHT = VA_PLAT_HEIGHT + VA_WALL_DEPTH*2
