/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.6
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef DRAWING_WRAP_H
#define DRAWING_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Shape_draw(void* imarg1);
void _wrap_delete_Shape(void* imarg1);
void _wrap_Painter_drawShape(void* imarg1, void* imarg2);
void* _wrap_new_Painter();
void _wrap_delete_Painter(void* imarg1);

#ifdef __cplusplus
}
#endif

#endif

